### ISSUE TITLE
Problems with Cyrillic

### ISSUE THREAD

**Issue by RomanAverin** [schmidlorenz/alfred-ddgnext#2]
I have trouble finding the Cyrillic. 
![2016-12-18 17 01 24](https://cloud.githubusercontent.com/assets/124546/21293974/a3dc028c-c543-11e6-938f-6500a103bc56.png)

**Comment by lorenzschmid** [comment]
Thanks for opening this issue, I just fixed it and it seemed to work well with "спасибо".
